<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_server_model extends CI_Model
{

    public $table = 'data_server';
    public $id = 'id_server';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_server', $q);
	$this->db->or_like('id_server_child', $q);
	$this->db->or_like('ip_server', $q);
	$this->db->or_like('ip_server_public', $q);
	$this->db->or_like('port', $q);
	$this->db->or_like('name_server', $q);
	$this->db->or_like('os_username', $q);
	$this->db->or_like('os_password', $q);
	$this->db->or_like('db_username', $q);
	$this->db->or_like('db_password', $q);
	$this->db->or_like('portal_username', $q);
	$this->db->or_like('portal_password', $q);
	$this->db->or_like('type_server', $q);
	$this->db->or_like('level_server', $q);
	$this->db->or_like('os_server', $q);
	$this->db->or_like('hdd_server', $q);
	$this->db->or_like('ram_server', $q);
	$this->db->or_like('cpu_server', $q);
	$this->db->or_like('cpu_detail', $q);
	$this->db->or_like('hdd_detail', $q);
	$this->db->or_like('note_server', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_server', $q);
	$this->db->or_like('id_server_child', $q);
	$this->db->or_like('ip_server', $q);
	$this->db->or_like('ip_server_public', $q);
	$this->db->or_like('port', $q);
	$this->db->or_like('name_server', $q);
	$this->db->or_like('os_username', $q);
	$this->db->or_like('os_password', $q);
	$this->db->or_like('db_username', $q);
	$this->db->or_like('db_password', $q);
	$this->db->or_like('portal_username', $q);
	$this->db->or_like('portal_password', $q);
	$this->db->or_like('type_server', $q);
	$this->db->or_like('level_server', $q);
	$this->db->or_like('os_server', $q);
	$this->db->or_like('hdd_server', $q);
	$this->db->or_like('ram_server', $q);
	$this->db->or_like('cpu_server', $q);
	$this->db->or_like('cpu_detail', $q);
	$this->db->or_like('hdd_detail', $q);
	$this->db->or_like('note_server', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_server_model.php */
/* Location: ./application/models/Data_server_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-02-10 03:51:26 */
/* http://harviacode.com */