<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Subindikator_model extends CI_Model
{

    public $table = 'tsubindikator';
    public $tableindikator = 'tindikator';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('kdindikator', $q);
        $this->db->or_like('kdsubindikator', $q);
        $this->db->or_like('subindikator', $q);
        $this->db->or_like('date_created', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('kdindikator', $q);
        $this->db->or_like('kdsubindikator', $q);
        $this->db->or_like('subindikator', $q);
        $this->db->or_like('date_created', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->tableindikator, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Subindikator_model.php */
/* Location: ./application/models/Subindikator_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-30 02:14:26 */
/* http://harviacode.com */