<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Tlaporan_model extends CI_Model
{

	public $table = 'tlaporan';
	public $id = 'id';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// get all
	function get_all()
	{
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->table)->result();
	}

	// get data by id
	function get_by_id($kdsubindikator)
	{
		$this->db->query("SELECT * FROM `tlaporan` WHERE `kdsubindikator` = $kdsubindikator");
		return $this->db->get($this->table)->row();
	}

	// get total rows
	function total_rows($q = NULL)
	{
		$this->db->like('id', $q);
		$this->db->or_like('kdsubindikator', $q);
		$this->db->or_like('target', $q);
		$this->db->or_like('januari1', $q);
		$this->db->or_like('januari2', $q);
		$this->db->or_like('februari1', $q);
		$this->db->or_like('februari2', $q);
		$this->db->or_like('maret1', $q);
		$this->db->or_like('maret2', $q);
		$this->db->or_like('april1', $q);
		$this->db->or_like('april2', $q);
		$this->db->or_like('mei1', $q);
		$this->db->or_like('mei2', $q);
		$this->db->or_like('juni1', $q);
		$this->db->or_like('juni2', $q);
		$this->db->or_like('juli1', $q);
		$this->db->or_like('juli2', $q);
		$this->db->or_like('agustus1', $q);
		$this->db->or_like('agustus2', $q);
		$this->db->or_like('september1', $q);
		$this->db->or_like('september2', $q);
		$this->db->or_like('oktober1', $q);
		$this->db->or_like('oktober2', $q);
		$this->db->or_like('november1', $q);
		$this->db->or_like('november2', $q);
		$this->db->or_like('desember1', $q);
		$this->db->or_like('desember2', $q);
		$this->db->from($this->table);
		return $this->db->count_all_results();
	}

	// get data with limit and search
	function get_limit_data($limit, $start = 0, $q = NULL)
	{
		$this->db->order_by($this->id, $this->order);
		$this->db->like('id', $q);
		$this->db->or_like('kdsubindikator', $q);
		$this->db->or_like('target', $q);
		$this->db->or_like('januari1', $q);
		$this->db->or_like('januari2', $q);
		$this->db->or_like('februari1', $q);
		$this->db->or_like('februari2', $q);
		$this->db->or_like('maret1', $q);
		$this->db->or_like('maret2', $q);
		$this->db->or_like('april1', $q);
		$this->db->or_like('april2', $q);
		$this->db->or_like('mei1', $q);
		$this->db->or_like('mei2', $q);
		$this->db->or_like('juni1', $q);
		$this->db->or_like('juni2', $q);
		$this->db->or_like('juli1', $q);
		$this->db->or_like('juli2', $q);
		$this->db->or_like('agustus1', $q);
		$this->db->or_like('agustus2', $q);
		$this->db->or_like('september1', $q);
		$this->db->or_like('september2', $q);
		$this->db->or_like('oktober1', $q);
		$this->db->or_like('oktober2', $q);
		$this->db->or_like('november1', $q);
		$this->db->or_like('november2', $q);
		$this->db->or_like('desember1', $q);
		$this->db->or_like('desember2', $q);
		$this->db->limit($limit, $start);
		return $this->db->get($this->table)->result();
	}

	// insert data
	function insert($data)
	{
		$this->db->insert($this->table, $data);
	}

	// update data
	function update($kdsubindikator, $data)
	{
		$this->db->where('kdsubindikator', $kdsubindikator);
		$this->db->update('tlaporan', $data);
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
	}
}

/* End of file Tlaporan_model.php */
/* Location: ./application/models/Tlaporan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-30 08:19:28 */
/* http://harviacode.com */