<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Utama_model extends CI_Model
{

    public $table = 'tutama';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    public function tampil()
    {
        $query = $this->db->get('tutama');
        return $query->result_array();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('kode_jabatan', $q);
        $this->db->or_like('nama_jabatan', $q);
        $this->db->or_like('jpt_utama', $q);
        $this->db->or_like('jpt_madya', $q);
        $this->db->or_like('jpt_pratama', $q);
        $this->db->or_like('administrator', $q);
        $this->db->or_like('pengawas', $q);
        $this->db->or_like('pelaksana', $q);
        $this->db->or_like('jabatan_fungsional', $q);
        $this->db->or_like('ikhtisar_jabatan', $q);
        $this->db->or_like('pend_formal', $q);
        $this->db->or_like('pend_pelatihan', $q);
        $this->db->or_like('pengalaman_kerja', $q);
        $this->db->or_like('prestasi', $q);
        $this->db->or_like('kelas_jabatan', $q);
        $this->db->or_like('date_created', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('kode_jabatan', $q);
        $this->db->or_like('nama_jabatan', $q);
        $this->db->or_like('jpt_utama', $q);
        $this->db->or_like('jpt_madya', $q);
        $this->db->or_like('jpt_pratama', $q);
        $this->db->or_like('administrator', $q);
        $this->db->or_like('pengawas', $q);
        $this->db->or_like('pelaksana', $q);
        $this->db->or_like('jabatan_fungsional', $q);
        $this->db->or_like('ikhtisar_jabatan', $q);
        $this->db->or_like('pend_formal', $q);
        $this->db->or_like('pend_pelatihan', $q);
        $this->db->or_like('pengalaman_kerja', $q);
        $this->db->or_like('prestasi', $q);
        $this->db->or_like('kelas_jabatan', $q);
        $this->db->or_like('date_created', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Utama_model.php */
/* Location: ./application/models/Utama_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-24 07:37:15 */
/* http://harviacode.com */